/**
7. Create a List of 10 String with your own values
   - create a Integer variable called randomIndex
   - assign the value to random Integer between (between 0-9)
   - use above index to print out the value at that index */

   List<String> colors = new List<String>{
    'Blue',
    'Green',
    'Yellow',
    'Orange',
    'White',
    'Black',
    'Purple',
    'Pink',
    'Red',
    'Brown'
   };
   Integer randomIndex =1;
   System.debug(colors.get(randomIndex));
