//public is a keyword to define access level 
//known as access modifier, there are couple of them we will learn later
//class: indicate this is a class
//phone: identifier, the name of the class
//{ any code need to go in here, can not go outside}
// the moment the class exists, it can be a DataType 
// meaning, you can create a variable of that type, a new instance (object) of that type
// and assign to the variable and much more 
public class Phone {
    // a phoe has attributes or charachteristics 
    // brand, price, memory size 
    // instance variable|field 
 public String brand;   
 public Decimal price;
 public Integer memorySize;   

}