/**Create a loop that print as below 
Sample Lead 1
Sample Lead 2
...
Sample Lead 10*/

for (integer num = 1; num <=10; num++){
system.debug('Sample Lead ' + num);
}
 
 system.debug('--------------------------');

/**  Create a Loop that print as below to generate sample first name last name 
TestFirst1  ,  TestLast1
TestFirst2  ,  TestLast2
TestFirst3  ,  TestLast3
TestFirst4  ,  TestLast4
*/

for (integer i = 1; i <= 4; i++){
    system.debug('TestFirst'+ i+' , '+'TestLast' + i);
}

